### ISSUE TITLE
Unable to evaluate model due to nonexistent User/Config directory in Dolphin

### ISSUE THREAD

**Issue by naltieri** [vladfi1/slippi-ai#25]
Hey! Thanks for this _awesome_ project and for making it open source and so easy to use. I managed to train the fox ditto model on google colab (and happy to upload the experiment files to allow others to have a pre-trained model).  However, when I try to evaluate the model on OSX I get:
```
python eval_self.py with saved_model_path=~/Downloads/experiments/2021-10-31_dccfa16f1a3767f6/saved_model/ dolphin_path=/Applications/Dolphin.app iso_path=isos/ssbm.iso

2021-10-31 16:53:33.641164: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING - eval - No observers have been added to this run
INFO - eval - Running command 'main'
INFO - eval - Started
ERROR - eval - Failed after 0:00:00!
Traceback (most recent calls WITHOUT Sacred internals):
  File "eval_self.py", line 27, in main
    blocking_input=True,
  File "/Users/nick/.local/lib/python3.6/site-packages/melee/console.py", line 98, in __init__
    _copytree_safe(self._get_dolphin_home_path(), temp_dir)
  File "/Users/nick/.local/lib/python3.6/site-packages/melee/console.py", line 51, in _copytree_safe
    shutil.copytree(src, dst, ignore=_ignore_fifos)
  File "/Users/nick/anaconda3/envs/hci_ssbm/lib/python3.6/shutil.py", line 315, in copytree
    names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: '/Applications/Dolphin.app/Contents/Resources/User/'
```

I've tried creating a dummy directory manually, but then run into:
```
python eval_cpu.py with saved_model_path=~/Downloads/experiments/2021-10-31_dccfa16f1a3767f6/saved_model/ dolphin_path=/Applications/Dolphin.app iso_path=isos/ssbm.iso

2021-10-31 19:28:11.733256: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING - eval - No observers have been added to this run
INFO - eval - Running command 'main'
INFO - eval - Started
ERROR - eval - Failed after 0:00:00!
Traceback (most recent calls WITHOUT Sacred internals):
  File "eval_cpu.py", line 28, in main
    blocking_input=True,
  File "/Users/nick/.local/lib/python3.6/site-packages/melee/console.py", line 137, in __init__
    raise InvalidDolphinPath(self._get_dolphin_config_path())
melee.console.InvalidDolphinPath: /Applications/Dolphin.app/Contents/Resources/User/Config/
```

Is  /Applications/Dolphin.app the right path? By the way I'm using dolphin 5.0-15260. I'm not sure if that matters.

**Comment by ryanmcgrath** [comment]
Slippi Dolphin was renamed to `/Applications/Slippi Dolphin.app` some time ago, just fyi to all.

**Comment by naltieri** [comment]
Huh, I installed the most recent version last week and I see:
`/Applications/Slippi\ Launcher.app`
(which unfortunately does not seem to have User under resources either.

**Comment by ryanmcgrath** [comment]
Ah, yes - if you're using the Launcher and not a standalone `Slippi Dolphin.app`, then your path would be ` ~/Library/Application\ Support/Slippi\ Launcher/netplay/Slippi\ Dolphin.app`.

**Comment by naltieri** [comment]
Yes! I see it there. I didn't realize there was a distinction! I see the corresponding folder :) I'm running into some additional issues when running the evaluation related to the file path, but I'll spend some time figuring it out. Thanks so much! This was super helpful.

**Comment by naltieri** [comment]
Ah I figured out what my other issue was. It was that it arguments need to be absolute directories (ie it won't find it if you do ~/PATH). Now I'm running into another issue where it spits out a bunch of "unused variables" warnings and doesn't do anything when Dolphin starts. But that's a separate issue and I'll spend more time investigating. Thanks again Ryan!
